#CitAccountBundle:
    #resource: "@CitAccountBundle/Resources/config/routing.yml"
    #prefix:   /

CitTestBundle:
    resource: "@CitTestBundle/Resources/config/routing.yml"
    prefix:   /

CitUserBundle:
    resource: "@CitUserBundle/Resources/config/routing.yml"
    prefix:   /

AcmeHelloBundle:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

#AcmeDemoBundle:
#    resource: "@AcmeDemoBundle/Resources/config/routing.yml" le fichier routing n'existe pas
#    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
