testuser:
    pattern:  /
    defaults: { _controller: "CitTestBundle:TestUser:index" }

testuser_show:
    pattern:  /{id}/show
    defaults: { _controller: "CitTestBundle:TestUser:show" }

testuser_new:
    pattern:  /new
    defaults: { _controller: "CitTestBundle:TestUser:new" }

testuser_create:
    pattern:  /create
    defaults: { _controller: "CitTestBundle:TestUser:create" }
    requirements: { _method: post }

testuser_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "CitTestBundle:TestUser:edit" }

testuser_update:
    pattern:  /{id}/update
    defaults: { _controller: "CitTestBundle:TestUser:update" }
    requirements: { _method: post }

testuser_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "CitTestBundle:TestUser:delete" }
    requirements: { _method: post }
