CitUserBundle_user:
    resource: "@CitUserBundle/Resources/config/routing/user.yml"
    prefix:   /cruduser

CitUserBundle_homepage:
    pattern:  /myaccount
    defaults: { _controller: CitUserBundle:Default:index }

CitUserBundle_editinfospage:
    pattern:  /myaccount/editinfos
    defaults: { _controller: CitUserBundle:Default:editInfos }

CitUserBundle_changepwd:
    pattern:  /myaccount/changepwd
    defaults: { _controller: CitUserBundle:Default:changePwd }

CitUserBundle_deletemyaccount:
    pattern:  /myaccount/delete
    defaults: { _controller: CitUserBundle:Default:deleteMyAccount }

CitUserBundle_deleteuseraccount:
    pattern:  /myaccount/{id}/deleteuser
    defaults: { _controller: CitUserBundle:Default:deleteUser }
    requirements: { _method: post }


