<?php

namespace Cit\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * VoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageRepository extends EntityRepository
{
}